# Generated by Django 5.0.6 on 2024-09-18 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('published_at', models.DateTimeField()),
                ('url', models.URLField()),
                ('category', models.CharField(default='general', max_length=100)),
                ('country', models.CharField(default='us', max_length=100)),
            ],
        ),
    ]
